// Generated by CoffeeScript 1.3.3
(function() {

  ig.module("game.teknosparx.main").requires("impact.game", "game.teknosparx.levels.world", "game.teknosparx.entities.robot").defines(function() {
    var Teknosparx;
    Teknosparx = ig.Game.extend({
      panelBg: new ig.Image("media/teknosparx/tekno_bg.png"),
      init: function() {
        ig.input.bind(ig.KEY.MOUSE1, "primary_button");
        ig.game.loadLevel(LevelWorld);
        return ig.game.spawnEntity(Robot, 80, 160);
      },
      update: function() {
        this.parent();
        if (ig.input.pressed("primary_button")) {
          this.enterDragState();
        }
        if (ig.input.released("primary_button")) {
          this.exitDragState();
        }
        if (this.dragState) {
          ig.game.screen.x = this.firstScreenX + (this.firstMouseDragX - ig.input.mouse.x);
          ig.game.screen.y = this.firstScreenY + (this.firstMouseDragY - ig.input.mouse.y);
          ig.game.screen.x = ig.game.screen.x.limit(0, (75 - 20) * 16);
          return ig.game.screen.y = ig.game.screen.y.limit(0, (50 - 15) * 16);
        }
      },
      enterDragState: function() {
        this.firstMouseDragX = ig.input.mouse.x;
        this.firstMouseDragY = ig.input.mouse.y;
        this.firstScreenX = ig.game.screen.x;
        this.firstScreenY = ig.game.screen.y;
        return this.dragState = true;
      },
      exitDragState: function() {
        return this.dragState = false;
      },
      draw: function() {
        this.parent();
        return this.panelBg.draw(0, 220);
      }
    });
    return ig.main('#canvas', Teknosparx, 60, 320, 240, 2);
  });

}).call(this);
