// Generated by CoffeeScript 1.3.3
(function() {

  ig.module("game.teknosparx.entities.robot").requires("impact.animation", "impact.entity").defines(function() {
    return window.Robot = ig.Entity.extend({
      size: {
        x: 16,
        y: 16
      },
      animSheet: new ig.AnimationSheet("media/teknosparx/robot.png", 16, 16),
      init: function(x, y, settings) {
        this.parent(x, y, settings);
        this.addAnim("idle", 1.0, [0]);
        this.addAnim("moveSouth", 0.1, [0, 1]);
        this.addAnim("moveNorth", 0.1, [2, 3]);
        this.addAnim("moveWest", 0.1, [4, 5]);
        this.addAnim("moveEast", 0.1, [6, 7]);
        return this.currentAnim = this.anims.moveSouth;
      },
      update: function() {
        return this.parent();
      }
    });
  });

}).call(this);
