// Generated by CoffeeScript 1.3.3
(function() {

  ig.module("game.entities.placeable").requires("impact.entity", "impact.game").defines(function() {
    return window.Placeable = ig.Entity.extend({
      size: {
        x: 16,
        y: 16
      },
      collides: ig.Entity.COLLIDES.PASSIVE,
      mineralsConsumed: 0,
      mineralsProduced: 0,
      energyConsumed: 0,
      energyProduced: 0,
      productionProduced: 0,
      productionCost: 0,
      research: 0,
      placed: false,
      init: function(x, y, settings) {
        return this.parent(x, y, settings);
      },
      canPlace: function() {
        if (this.getMineralsConsumed() > ig.game.mineralsProduced - ig.game.mineralsConsumed) {
          ig.game.alerts.push({
            time: 120,
            text: "Can't place building: not enough minerals."
          });
          return false;
        }
        if (this.getEnergyConsumed() > ig.game.energyProduced - ig.game.energyConsumed) {
          ig.game.alerts.push({
            time: 120,
            text: "Can't place building: not enough energy."
          });
          return false;
        }
        return true;
      },
      place: function() {
        this.placed = true;
        return this.currentAnim.alpha = 1;
      },
      getMineralsConsumed: function() {
        return this.mineralsConsumed;
      },
      getMineralsProduced: function() {
        return this.mineralsProduced;
      },
      getEnergyConsumed: function() {
        return this.energyConsumed;
      },
      getEnergyProduced: function() {
        return this.energyProduced;
      },
      getProductionProduced: function() {
        return this.productionProduced;
      },
      getProductionCost: function() {
        return this.productionCost;
      },
      getResearch: function() {
        return this.research;
      }
    });
  });

}).call(this);
