// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.windmaster.entities.quantopto').requires('impact.game', 'game.windmaster.entities.placeable').defines(function() {
    return window.QuantomOptoComptroller = Placeable.extend({
      size: {
        x: 16,
        y: 16
      },
      collides: ig.Entity.COLLIDES.PASSIVE,
      animSheet: new ig.AnimationSheet("media/windmaster/qo_comptroller.png", 16, 16),
      energyConsumed: 10,
      productionCost: 1000,
      name: "Quantum-Optical Comptroller",
      init: function(x, y, settings) {
        this.parent(x, y, settings);
        return this.addAnim("idle", 0.2, [0, 1, 2, 3]);
      },
      getEnergyProduced: function() {
        var energyProduced, generator, generators, _i, _len;
        generators = (function() {
          var _i, _len, _ref, _results;
          _ref = ig.game.getEntitiesByType(Generator);
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            generator = _ref[_i];
            if (generator.placed) {
              _results.push(generator);
            }
          }
          return _results;
        })();
        energyProduced = 0;
        for (_i = 0, _len = generators.length; _i < _len; _i++) {
          generator = generators[_i];
          if (generator.distanceTo(this) < 30) {
            energyProduced += 5;
          }
        }
        return energyProduced;
      }
    });
  });

}).call(this);
