// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.windmaster.entities.supercollider').requires('impact.game', 'game.windmaster.entities.placeable').defines(function() {
    return window.Supercollider = Placeable.extend({
      size: {
        x: 16,
        y: 16
      },
      collides: ig.Entity.COLLIDES.PASSIVE,
      animSheet: new ig.AnimationSheet("media/windmaster/supercollider.png", 16, 16),
      research: 30,
      energyConsumed: 50,
      productionCost: 1000,
      name: "Supercollider",
      init: function(x, y, settings) {
        this.parent(x, y, settings);
        return this.addAnim("idle", 0.1, [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
      },
      getResearch: function() {
        var center, research, researchCenters, _i, _len;
        researchCenters = (function() {
          var _i, _len, _ref, _results;
          _ref = ig.game.getEntitiesByType(ResearchCenter);
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            center = _ref[_i];
            if (center.placed) {
              _results.push(center);
            }
          }
          return _results;
        })();
        research = this.research;
        for (_i = 0, _len = researchCenters.length; _i < _len; _i++) {
          center = researchCenters[_i];
          if (center.distanceTo(this) < 30) {
            research += 10;
          }
        }
        return research;
      }
    });
  });

}).call(this);
